'use client'

import { useState } from 'react'
import {
  Box,
  Typography,
  TextField,
  Button,
  CircularProgress,
  Stack,
  Alert,
  Divider,
} from '@mui/material'
import {
  CheckCircle as ApproveIcon,
  Delete as DiscardIcon,
  AutoFixHigh as RepolishIcon,
} from '@mui/icons-material'

interface NarrationReviewPanelProps {
  subjectName?: string
  originalContent: string
  initialNarratedContent: string
  narrationModel?: string | null
  onSaveDraft: (narratedContent: string) => Promise<void>
  onApprove: (narratedContent: string) => Promise<void>
  onDiscard: () => Promise<void>
  onRepolish: () => Promise<void>
}

export function NarrationReviewPanel({
  subjectName,
  originalContent,
  initialNarratedContent,
  narrationModel,
  onSaveDraft,
  onApprove,
  onDiscard,
  onRepolish,
}: NarrationReviewPanelProps) {
  const [draft, setDraft] = useState(initialNarratedContent)
  const [busyAction, setBusyAction] = useState<null | 'save' | 'approve' | 'discard' | 'repolish'>(null)
  const [error, setError] = useState<string | null>(null)

  const isDirty = draft.trim() !== initialNarratedContent.trim()
  const subject = subjectName?.trim() || 'the subject'

  const run = async (action: 'save' | 'approve' | 'discard' | 'repolish', fn: () => Promise<void>) => {
    setBusyAction(action)
    setError(null)
    try {
      await fn()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Action failed')
    } finally {
      setBusyAction(null)
    }
  }

  return (
    <Box
      sx={{
        backgroundColor: '#fcf9f4',
        border: '1px solid #d0e3e6',
        borderRadius: 3,
        p: 3,
        mb: 4,
      }}
    >
      <Typography variant="subtitle1" sx={{ fontWeight: 600, color: '#16334a', mb: 0.5 }}>
        Review {subject}'s narration
      </Typography>
      <Typography variant="body2" sx={{ color: '#546669', mb: 2 }}>
        Read through the first-person rewrite. Edit anything that sounds off, then approve. This is what the cloned voice will read. The original story is unchanged.
      </Typography>

      <Box sx={{ display: 'flex', flexDirection: { xs: 'column', md: 'row' }, gap: 3, mb: 2 }}>
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Typography variant="overline" sx={{ color: '#888', fontWeight: 600 }}>
            Original
          </Typography>
          <Box
            sx={{
              backgroundColor: '#f6f3ee',
              borderRadius: 2,
              p: 2,
              maxHeight: 360,
              overflowY: 'auto',
              whiteSpace: 'pre-wrap',
              fontSize: '0.95rem',
              color: '#333',
              lineHeight: 1.6,
            }}
          >
            {originalContent}
          </Box>
        </Box>
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Typography variant="overline" sx={{ color: '#888', fontWeight: 600 }}>
            Narration (first-person)
          </Typography>
          <TextField
            multiline
            fullWidth
            minRows={10}
            maxRows={18}
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            sx={{
              '& .MuiOutlinedInput-root': {
                backgroundColor: '#ffffff',
                borderRadius: 2,
                fontSize: '0.95rem',
                lineHeight: 1.6,
              },
            }}
          />
        </Box>
      </Box>

      {narrationModel && (
        <Typography variant="caption" sx={{ color: '#999', fontStyle: 'italic', display: 'block', mb: 2 }}>
          Draft generated by {narrationModel}. Always review for accuracy — AI rewrites can drift.
        </Typography>
      )}

      {error && (
        <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError(null)}>
          {error}
        </Alert>
      )}

      <Divider sx={{ mb: 2 }} />

      <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} alignItems={{ sm: 'center' }}>
        <Button
          onClick={() => run('approve', () => onApprove(draft))}
          variant="contained"
          startIcon={busyAction === 'approve' ? <CircularProgress size={16} sx={{ color: 'white' }} /> : <ApproveIcon />}
          disabled={!!busyAction || draft.trim().length === 0}
          sx={{
            backgroundColor: '#16334a',
            color: 'white',
            textTransform: 'none',
            fontWeight: 600,
            '&:hover': { backgroundColor: '#2e4a62' },
          }}
        >
          {busyAction === 'approve' ? 'Approving…' : 'Approve narration'}
        </Button>

        {isDirty && (
          <Button
            onClick={() => run('save', () => onSaveDraft(draft))}
            variant="outlined"
            disabled={!!busyAction || draft.trim().length === 0}
            sx={{ textTransform: 'none', fontWeight: 600, borderColor: '#16334a', color: '#16334a' }}
          >
            {busyAction === 'save' ? 'Saving…' : 'Save draft'}
          </Button>
        )}

        <Box sx={{ flexGrow: 1 }} />

        <Button
          onClick={() => run('repolish', onRepolish)}
          startIcon={busyAction === 'repolish' ? <CircularProgress size={16} /> : <RepolishIcon />}
          disabled={!!busyAction}
          sx={{ textTransform: 'none', color: '#546669' }}
        >
          {busyAction === 'repolish' ? 'Re-polishing…' : 'Re-polish with AI'}
        </Button>

        <Button
          onClick={() => run('discard', onDiscard)}
          startIcon={busyAction === 'discard' ? <CircularProgress size={16} /> : <DiscardIcon />}
          color="error"
          disabled={!!busyAction}
          sx={{ textTransform: 'none' }}
        >
          {busyAction === 'discard' ? 'Discarding…' : 'Discard'}
        </Button>
      </Stack>
    </Box>
  )
}
