ALTER TABLE "Story" ADD COLUMN "locationCity" TEXT;
ALTER TABLE "Story" ADD COLUMN "locationState" TEXT;
ALTER TABLE "Story" ADD COLUMN "locationLat" DOUBLE PRECISION;
ALTER TABLE "Story" ADD COLUMN "locationLng" DOUBLE PRECISION;
